# render.yaml
# This version explicitly specifies the 'free' plan for the service.

services:
  # A unique name for our web service
  - name: stock-screener-app
    # The runtime specifies the language environment.
    runtime: python
    # Explicitly set the service plan to the free tier.
    plan: free
    # The type of service. 'web' means it will have a public URL.
    type: web
    # The command to install all our Python packages.
    buildCommand: "pip install -r requirements.txt"
    # The command to start the web server.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    # Health check path to ensure the app is running before going live.
    healthCheckPath: /
    # Environment variables section.
    envVars:
      # This sets the specific Python version for the build environment.
      - key: PYTHON_VERSION
        value: "3.11"
